# 기본 numpy 사용법

In [1]:
import numpy as np

In [3]:
A = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
B = np.array([
    [0,1],
    [2,3]
])
B

array([[0, 1],
       [2, 3]])

In [9]:
C = np.random.rand(3,5)
C

array([[0.08900715, 0.97499628, 0.92014735, 0.60687007, 0.32777492],
       [0.24601066, 0.3450862 , 0.00155207, 0.26587554, 0.57724925],
       [0.22520722, 0.9494536 , 0.52999214, 0.96231831, 0.97549759]])

In [10]:
D = np.zeros((2,4)) #괄호 두개써야함!!
D

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [11]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
A[0][2] #indexing은 0부터!!

3

In [14]:
E = np.random.rand(3,3)
E

array([[0.10874036, 0.00133393, 0.94842064],
       [0.76855366, 0.18309706, 0.72119271],
       [0.45060964, 0.81977233, 0.71095085]])

In [15]:
A+E

array([[1.10874036, 2.00133393, 3.94842064],
       [4.76855366, 5.18309706, 6.72119271],
       [7.45060964, 8.81977233, 9.71095085]])

In [16]:
5*A

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [18]:
np.dot(A,E) #내적곱

array([[ 2.99767661,  2.82684503,  4.52365861],
       [ 6.98138759,  5.83945498, 11.6653512 ],
       [10.96509857,  8.85206493, 18.8070438 ]])

In [19]:
A@E #내적곱

array([[ 2.99767661,  2.82684503,  4.52365861],
       [ 6.98138759,  5.83945498, 11.6653512 ],
       [10.96509857,  8.85206493, 18.8070438 ]])

In [22]:
A@E + (A+2*E) #곱하기 부터, 괄호 먼저

array([[ 4.21515732,  4.82951289,  9.42049989],
       [12.51849491, 11.2056491 , 19.10773662],
       [18.86631786, 18.49160959, 29.2289455 ]])

In [27]:
A_transpose = np.transpose(A)
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [28]:
A_transpose

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [29]:
A_transpose = A.T
A_transpose

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [31]:
I = np.identity(3)
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [32]:
A@I

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [33]:
A_inverse = np.linalg.pinv(A) 
#linear algegra p inverse; 역행렬 없는 경우도 가장 비슷한 행렬 리턴해줌
A_inverse

array([[-6.38888889e-01, -1.66666667e-01,  3.05555556e-01],
       [-5.55555556e-02,  1.38777878e-16,  5.55555556e-02],
       [ 5.27777778e-01,  1.66666667e-01, -1.94444444e-01]])

In [38]:
A@A_inverse

array([[ 0.83333333,  0.33333333, -0.16666667],
       [ 0.33333333,  0.33333333,  0.33333333],
       [-0.16666667,  0.33333333,  0.83333333]])

In [36]:
ab = np.array([[1,-1,2],
             [3,2,2],
             [4,1,2]])
ab_i = np.linalg.pinv(ab)

In [37]:
ab @ab_i

array([[ 1.00000000e+00,  6.66133815e-16, -1.11022302e-15],
       [-2.22044605e-16,  1.00000000e+00, -6.66133815e-16],
       [ 0.00000000e+00,  2.22044605e-16,  1.00000000e+00]])

In [39]:
C_inverse = np.linalg.pinv(C)

In [40]:
C_inverse

array([[ 0.85752696,  2.74258346, -1.6323689 ],
       [ 1.0789051 ,  1.57581195, -1.11471571],
       [ 0.90753932, -0.23546574, -0.42043615],
       [-1.38479373, -3.15858262,  2.57112695],
       [-0.37505776,  1.07693445,  0.17896243]])

In [41]:
C@C_inverse

array([[ 1.00000000e+00, -7.86977911e-16, -1.07942731e-16],
       [-1.48150193e-16,  1.00000000e+00,  1.09250935e-16],
       [-4.29871596e-16, -5.02811855e-16,  1.00000000e+00]])